const sampleUsers = [
  {
    username: "gamerpro99",
    password: "hashedpassword123",
    phone: "9876543210",
    email: "gamerpro99@example.com",
    role: "User",
    wishlist: ["PC-12", "C-05"],
    bookings: [],
  },
  {
    username: "shadowhunter",
    password: "hashedpassword456",
    phone: "9123456780",
    email: "shadowhunter@example.com",
    role: "User",
    wishlist: ["PC-01"],
    bookings: [],
  },
  {
    username: "pixelqueen",
    password: "hashedpassword789",
    phone: "9988776655",
    email: "pixelqueen@example.com",
    role: "User",
    wishlist: ["C-01", "C-02"],
    bookings: [],
  },
  {
    username: "noobmaster69",
    password: "hashedpassword321",
    phone: "9090909090",
    email: "noobmaster69@example.com",
    role: "User",
    wishlist: [],
    bookings: [],
  },
  {
    username: "cyberknight",
    password: "hashedpassword654",
    phone: "8800554433",
    email: "cyberknight@example.com",
    role: "User",
    wishlist: ["PC-50", "PC-49"],
    bookings: [],
  },
  {
    username: "vr_addict",
    password: "hashedpassword987",
    phone: "7001234567",
    email: "vraddict@example.com",
    role: "User",
    wishlist: ["C-10"],
    bookings: [],
  },
  {
    username: "esportslegend",
    password: "hashedpassword159",
    phone: "8123456789",
    email: "esportslegend@example.com",
    role: "User",
    wishlist: ["PC-25", "PC-26"],
    bookings: [],
  },
  {
    username: "arcadehero",
    password: "hashedpassword753",
    phone: "9776655443",
    email: "arcadehero@example.com",
    role: "User",
    wishlist: [],
    bookings: [],
  },
  {
    username: "consoleking",
    password: "hashedpassword852",
    phone: "9556677880",
    email: "consoleking@example.com",
    role: "User",
    wishlist: ["C-07", "C-08"],
    bookings: [],
  },
  {
    username: "nexusadmin",
    password: "hashedpassword999",
    phone: "9001122334",
    email: "admin@nexusgaming.com",
    role: "Admin",
    wishlist: [],
    bookings: [],
  },
];

module.exports = { data: sampleUsers };
